-- Seed data for Employee Feedback Analyzer
-- This file contains comprehensive sample feedback data with enhanced sentiment analysis

-- Insert sample topics first
INSERT INTO topics (name, description, keywords) VALUES
('Work Environment', 'Feedback about the physical and cultural work environment', ARRAY['office', 'culture', 'atmosphere', 'colleagues', 'team', 'environment']),
('Management', 'Feedback about leadership and management practices', ARRAY['manager', 'leadership', 'supervision', 'guidance', 'support', 'communication']),
('Compensation', 'Feedback about salary, benefits, and compensation', ARRAY['salary', 'pay', 'benefits', 'compensation', 'bonus', 'raise']),
('Career Growth', 'Feedback about professional development and growth opportunities', ARRAY['career', 'growth', 'development', 'promotion', 'learning', 'training']),
('Work-Life Balance', 'Feedback about work-life balance and flexibility', ARRAY['balance', 'flexibility', 'hours', 'remote', 'schedule', 'time']),
('Technology', 'Feedback about tools, systems, and technology', ARRAY['tools', 'software', 'systems', 'technology', 'equipment', 'IT']),
('Communication', 'Feedback about internal communication and transparency', ARRAY['communication', 'meetings', 'updates', 'transparency', 'information', 'news']),
('Recognition', 'Feedback about recognition and appreciation', ARRAY['recognition', 'appreciation', 'feedback', 'praise', 'achievement', 'reward']);

-- Comprehensive feedback submissions with enhanced sentiment data
INSERT INTO feedback_submissions (
    department_id,
    is_anonymous,
    submitter_name,
    overall_rating,
    work_environment_rating,
    management_rating,
    compensation_rating,
    growth_opportunities_rating,
    comments,
    suggestions,
    redacted_comments,
    redacted_suggestions,
    contains_pii,
    sentiment_score,
    sentiment_label,
    confidence_score,
    sentiment_intensity,
    work_environment_sentiment,
    work_environment_sentiment_label,
    work_environment_intensity,
    management_sentiment,
    management_sentiment_label,
    management_intensity,
    compensation_sentiment,
    compensation_sentiment_label,
    compensation_intensity,
    growth_opportunities_sentiment,
    growth_opportunities_sentiment_label,
    growth_opportunities_intensity,
    ip_hash,
    user_agent_hash,
    submitted_at
) VALUES

-- Engineering Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    4,
    4,
    3,
    3,
    4,
    'Great team culture and interesting projects. The work environment is collaborative and supportive. However, management could be more transparent about company direction and compensation could be more competitive.',
    'Consider implementing regular 1-on-1s with managers and more transparent salary bands.',
    'Great team culture and interesting projects. The work environment is collaborative and supportive. However, management could be more transparent about company direction and compensation could be more competitive.',
    'Consider implementing regular 1-on-1s with managers and more transparent salary bands.',
    false,
    0.2,
    'positive',
    0.85,
    'moderate',
    0.6,
    'positive',
    'moderate',
    -0.3,
    'negative',
    'mild',
    -0.4,
    'negative',
    'moderate',
    0.5,
    'positive',
    'moderate',
    'hash1',
    'ua_hash1',
    NOW() - INTERVAL '1 day'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'Sarah Chen',
    5,
    5,
    4,
    4,
    5,
    'Absolutely love working here! The team is amazing, the projects are challenging, and I feel like I am constantly learning and growing. Management is supportive and the work-life balance is excellent.',
    'Keep doing what you are doing! Maybe add more team building activities.',
    'Absolutely love working here! The team is amazing, the projects are challenging, and I feel like I am constantly learning and growing. Management is supportive and the work-life balance is excellent.',
    'Keep doing what you are doing! Maybe add more team building activities.',
    false,
    0.8,
    'positive',
    0.92,
    'strong',
    0.9,
    'positive',
    'strong',
    0.7,
    'positive',
    'moderate',
    0.6,
    'positive',
    'moderate',
    0.8,
    'positive',
    'strong',
    'hash2',
    'ua_hash2',
    NOW() - INTERVAL '2 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    2,
    2,
    2,
    2,
    3,
    'The workload is overwhelming and unrealistic. Management keeps adding more projects without considering capacity. The compensation is below market rate and there is no clear path for advancement.',
    'Need better project planning and realistic deadlines. Also, please review salary bands.',
    'The workload is overwhelming and unrealistic. Management keeps adding more projects without considering capacity. The compensation is below market rate and there is no clear path for advancement.',
    'Need better project planning and realistic deadlines. Also, please review salary bands.',
    false,
    -0.7,
    'negative',
    0.88,
    'strong',
    -0.3,
    'negative',
    'mild',
    -0.8,
    'negative',
    'strong',
    -0.9,
    'negative',
    'strong',
    -0.4,
    'negative',
    'moderate',
    'hash3',
    'ua_hash3',
    NOW() - INTERVAL '3 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'David Kim',
    4,
    4,
    4,
    3,
    4,
    'Solid engineering team with good technical challenges. The codebase is well-maintained and the development process is efficient. Management understands technical requirements well.',
    'More opportunities for technical leadership and architecture decisions.',
    'Solid engineering team with good technical challenges. The codebase is well-maintained and the development process is efficient. Management understands technical requirements well.',
    'More opportunities for technical leadership and architecture decisions.',
    false,
    0.4,
    'positive',
    0.78,
    'moderate',
    0.6,
    'positive',
    'moderate',
    0.5,
    'positive',
    'moderate',
    0.2,
    'positive',
    'mild',
    0.7,
    'positive',
    'moderate',
    'hash4',
    'ua_hash4',
    NOW() - INTERVAL '4 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    1,
    1,
    1,
    1,
    2,
    'Terrible place to work. Toxic environment, poor management, unrealistic expectations, and terrible compensation. I regret joining this company.',
    'Complete overhaul of management and company culture needed.',
    'Terrible place to work. Toxic environment, poor management, unrealistic expectations, and terrible compensation. I regret joining this company.',
    'Complete overhaul of management and company culture needed.',
    false,
    -0.9,
    'negative',
    0.95,
    'extreme',
    -0.8,
    'negative',
    'strong',
    -0.9,
    'negative',
    'extreme',
    -0.9,
    'negative',
    'extreme',
    -0.6,
    'negative',
    'strong',
    'hash5',
    'ua_hash5',
    NOW() - INTERVAL '5 days'
),

-- Product Department - Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Product'),
    false,
    'Maria Rodriguez',
    5,
    5,
    5,
    4,
    5,
    'Fantastic product team! Great collaboration, excellent leadership, and amazing growth opportunities. The work environment is creative and inspiring.',
    'Continue the great work! Maybe more cross-team collaboration.',
    'Fantastic product team! Great collaboration, excellent leadership, and amazing growth opportunities. The work environment is creative and inspiring.',
    'Continue the great work! Maybe more cross-team collaboration.',
    false,
    0.9,
    'positive',
    0.94,
    'strong',
    0.8,
    'positive',
    'strong',
    0.9,
    'positive',
    'strong',
    0.6,
    'positive',
    'moderate',
    0.9,
    'positive',
    'strong',
    'hash6',
    'ua_hash6',
    NOW() - INTERVAL '6 days'
),
(
    (SELECT id FROM departments WHERE name = 'Product'),
    true,
    null,
    4,
    4,
    4,
    3,
    4,
    'Good product team with interesting challenges. Management is supportive and the work environment is collaborative. Compensation could be better but growth opportunities are excellent.',
    'More competitive salary packages would be great.',
    'Good product team with interesting challenges. Management is supportive and the work environment is collaborative. Compensation could be better but growth opportunities are excellent.',
    'More competitive salary packages would be great.',
    false,
    0.5,
    'positive',
    0.82,
    'moderate',
    0.6,
    'positive',
    'moderate',
    0.7,
    'positive',
    'moderate',
    0.3,
    'positive',
    'mild',
    0.8,
    'positive',
    'strong',
    'hash7',
    'ua_hash7',
    NOW() - INTERVAL '7 days'
),

-- Sales Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    false,
    'James Wilson',
    3,
    3,
    2,
    4,
    3,
    'Sales team is okay but management pressure is intense. Good commission structure but unrealistic targets. Work environment is competitive but sometimes toxic.',
    'Better target setting and more realistic expectations needed.',
    'Sales team is okay but management pressure is intense. Good commission structure but unrealistic targets. Work environment is competitive but sometimes toxic.',
    'Better target setting and more realistic expectations needed.',
    false,
    -0.1,
    'neutral',
    0.75,
    'mild',
    0.2,
    'positive',
    'mild',
    -0.6,
    'negative',
    'strong',
    0.7,
    'positive',
    'moderate',
    0.1,
    'neutral',
    'mild',
    'hash8',
    'ua_hash8',
    NOW() - INTERVAL '8 days'
),
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    true,
    null,
    4,
    4,
    3,
    5,
    4,
    'Great sales team with excellent commission structure. Management is supportive and provides good training. Work environment is energetic and motivating.',
    'More team building activities would be beneficial.',
    'Great sales team with excellent commission structure. Management is supportive and provides good training. Work environment is energetic and motivating.',
    'More team building activities would be beneficial.',
    false,
    0.6,
    'positive',
    0.88,
    'moderate',
    0.7,
    'positive',
    'moderate',
    0.4,
    'positive',
    'moderate',
    0.8,
    'positive',
    'strong',
    0.6,
    'positive',
    'moderate',
    'hash9',
    'ua_hash9',
    NOW() - INTERVAL '9 days'
),

-- Marketing Department - Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Marketing'),
    false,
    'Lisa Thompson',
    4,
    4,
    4,
    3,
    4,
    'Creative marketing team with great ideas and supportive management. Work environment is inspiring and collaborative. Good compensation and excellent growth opportunities.',
    'More budget for marketing tools and campaigns.',
    'Creative marketing team with great ideas and supportive management. Work environment is inspiring and collaborative. Good compensation and excellent growth opportunities.',
    'More budget for marketing tools and campaigns.',
    false,
    0.7,
    'positive',
    0.89,
    'moderate',
    0.8,
    'positive',
    'strong',
    0.6,
    'positive',
    'moderate',
    0.5,
    'positive',
    'moderate',
    0.8,
    'positive',
    'strong',
    'hash10',
    'ua_hash10',
    NOW() - INTERVAL '10 days'
),
(
    (SELECT id FROM departments WHERE name = 'Marketing'),
    true,
    null,
    3,
    3,
    3,
    2,
    3,
    'Marketing team is decent but management could be more strategic. Work environment is okay but lacks creativity. Compensation is below average and growth opportunities are limited.',
    'More strategic direction and better compensation needed.',
    'Marketing team is decent but management could be more strategic. Work environment is okay but lacks creativity. Compensation is below average and growth opportunities are limited.',
    'More strategic direction and better compensation needed.',
    false,
    -0.2,
    'negative',
    0.79,
    'mild',
    0.1,
    'neutral',
    'mild',
    -0.3,
    'negative',
    'mild',
    -0.5,
    'negative',
    'moderate',
    -0.2,
    'negative',
    'mild',
    'hash11',
    'ua_hash11',
    NOW() - INTERVAL '11 days'
),

-- HR Department - Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'HR'),
    false,
    'Jennifer Adams',
    5,
    5,
    5,
    4,
    5,
    'Amazing HR team! Great leadership, supportive environment, and excellent growth opportunities. Management truly cares about employees and their development.',
    'Continue the excellent work in employee engagement.',
    'Amazing HR team! Great leadership, supportive environment, and excellent growth opportunities. Management truly cares about employees and their development.',
    'Continue the excellent work in employee engagement.',
    false,
    0.8,
    'positive',
    0.91,
    'strong',
    0.9,
    'positive',
    'strong',
    0.8,
    'positive',
    'strong',
    0.6,
    'positive',
    'moderate',
    0.9,
    'positive',
    'strong',
    'hash12',
    'ua_hash12',
    NOW() - INTERVAL '12 days'
),
(
    (SELECT id FROM departments WHERE name = 'HR'),
    true,
    null,
    4,
    4,
    4,
    3,
    4,
    'Good HR team with supportive management. Work environment is professional and collaborative. Compensation is fair and growth opportunities are good.',
    'More training programs for HR staff would be beneficial.',
    'Good HR team with supportive management. Work environment is professional and collaborative. Compensation is fair and growth opportunities are good.',
    'More training programs for HR staff would be beneficial.',
    false,
    0.5,
    'positive',
    0.83,
    'moderate',
    0.6,
    'positive',
    'moderate',
    0.7,
    'positive',
    'moderate',
    0.4,
    'positive',
    'mild',
    0.6,
    'positive',
    'moderate',
    'hash13',
    'ua_hash13',
    NOW() - INTERVAL '13 days'
),

-- Operations Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Operations'),
    false,
    'Michael Brown',
    3,
    3,
    2,
    3,
    3,
    'Operations team is efficient but management could be more organized. Work environment is functional but not inspiring. Compensation is average and growth opportunities are limited.',
    'Better organization and more growth opportunities needed.',
    'Operations team is efficient but management could be more organized. Work environment is functional but not inspiring. Compensation is average and growth opportunities are limited.',
    'Better organization and more growth opportunities needed.',
    false,
    -0.1,
    'neutral',
    0.77,
    'mild',
    0.2,
    'positive',
    'mild',
    -0.4,
    'negative',
    'moderate',
    0.1,
    'neutral',
    'mild',
    -0.2,
    'negative',
    'mild',
    'hash14',
    'ua_hash14',
    NOW() - INTERVAL '14 days'
),
(
    (SELECT id FROM departments WHERE name = 'Operations'),
    true,
    null,
    4,
    4,
    4,
    4,
    4,
    'Solid operations team with good management. Work environment is organized and efficient. Fair compensation and decent growth opportunities.',
    'More automation tools would improve efficiency.',
    'Solid operations team with good management. Work environment is organized and efficient. Fair compensation and decent growth opportunities.',
    'More automation tools would improve efficiency.',
    false,
    0.4,
    'positive',
    0.81,
    'moderate',
    0.5,
    'positive',
    'moderate',
    0.6,
    'positive',
    'moderate',
    0.5,
    'positive',
    'moderate',
    0.4,
    'positive',
    'mild',
    'hash15',
    'ua_hash15',
    NOW() - INTERVAL '15 days'
),

-- Finance Department - Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Finance'),
    false,
    'Robert Davis',
    4,
    4,
    4,
    4,
    4,
    'Professional finance team with excellent management. Work environment is structured and supportive. Good compensation and clear growth opportunities.',
    'More financial analysis tools would be helpful.',
    'Professional finance team with excellent management. Work environment is structured and supportive. Good compensation and clear growth opportunities.',
    'More financial analysis tools would be helpful.',
    false,
    0.6,
    'positive',
    0.87,
    'moderate',
    0.7,
    'positive',
    'moderate',
    0.8,
    'positive',
    'strong',
    0.6,
    'positive',
    'moderate',
    0.7,
    'positive',
    'moderate',
    'hash16',
    'ua_hash16',
    NOW() - INTERVAL '16 days'
),
(
    (SELECT id FROM departments WHERE name = 'Finance'),
    true,
    null,
    3,
    3,
    3,
    3,
    3,
    'Finance team is competent but management could be more innovative. Work environment is traditional but functional. Compensation is adequate and growth opportunities are standard.',
    'More innovative approaches and better technology needed.',
    'Finance team is competent but management could be more innovative. Work environment is traditional but functional. Compensation is adequate and growth opportunities are standard.',
    'More innovative approaches and better technology needed.',
    false,
    0.1,
    'neutral',
    0.74,
    'mild',
    0.3,
    'positive',
    'mild',
    0.2,
    'positive',
    'mild',
    0.3,
    'positive',
    'mild',
    0.2,
    'positive',
    'mild',
    'hash17',
    'ua_hash17',
    NOW() - INTERVAL '17 days'
),

-- Customer Success Department - Very Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Customer Success'),
    false,
    'Amanda Taylor',
    5,
    5,
    5,
    4,
    5,
    'Outstanding customer success team! Exceptional management, amazing work environment, and incredible growth opportunities. This is the best place I have ever worked.',
    'Keep up the fantastic work! Maybe more customer feedback integration.',
    'Outstanding customer success team! Exceptional management, amazing work environment, and incredible growth opportunities. This is the best place I have ever worked.',
    'Keep up the fantastic work! Maybe more customer feedback integration.',
    false,
    0.9,
    'positive',
    0.96,
    'strong',
    0.9,
    'positive',
    'strong',
    0.9,
    'positive',
    'strong',
    0.7,
    'positive',
    'moderate',
    0.9,
    'positive',
    'strong',
    'hash18',
    'ua_hash18',
    NOW() - INTERVAL '18 days'
),
(
    (SELECT id FROM departments WHERE name = 'Customer Success'),
    true,
    null,
    4,
    4,
    4,
    3,
    4,
    'Great customer success team with supportive management. Work environment is customer-focused and collaborative. Good compensation and excellent growth opportunities.',
    'More customer success tools and training would be beneficial.',
    'Great customer success team with supportive management. Work environment is customer-focused and collaborative. Good compensation and excellent growth opportunities.',
    'More customer success tools and training would be beneficial.',
    false,
    0.7,
    'positive',
    0.89,
    'moderate',
    0.8,
    'positive',
    'strong',
    0.7,
    'positive',
    'moderate',
    0.5,
    'positive',
    'moderate',
    0.8,
    'positive',
    'strong',
    'hash19',
    'ua_hash19',
    NOW() - INTERVAL '19 days'
),

-- Additional mixed sentiment entries for better data distribution
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'Alex Johnson',
    3,
    3,
    2,
    2,
    3,
    'Engineering team has potential but management needs improvement. Work environment is okay but could be more collaborative. Compensation is below market and growth opportunities are limited.',
    'Better management training and competitive salary needed.',
    'Engineering team has potential but management needs improvement. Work environment is okay but could be more collaborative. Compensation is below market and growth opportunities are limited.',
    'Better management training and competitive salary needed.',
    false,
    -0.3,
    'negative',
    0.76,
    'mild',
    0.1,
    'neutral',
    'mild',
    -0.5,
    'negative',
    'moderate',
    -0.6,
    'negative',
    'moderate',
    -0.3,
    'negative',
    'mild',
    'hash20',
    'ua_hash20',
    NOW() - INTERVAL '20 days'
),
(
    (SELECT id FROM departments WHERE name = 'Product'),
    true,
    null,
    2,
    2,
    1,
    2,
    2,
    'Product team is struggling with poor management and unclear direction. Work environment is chaotic and unorganized. Compensation is poor and there are no growth opportunities.',
    'Complete restructuring of product management needed.',
    'Product team is struggling with poor management and unclear direction. Work environment is chaotic and unorganized. Compensation is poor and there are no growth opportunities.',
    'Complete restructuring of product management needed.',
    false,
    -0.8,
    'negative',
    0.93,
    'strong',
    -0.6,
    'negative',
    'moderate',
    -0.9,
    'negative',
    'strong',
    -0.7,
    'negative',
    'moderate',
    -0.8,
    'negative',
    'strong',
    'hash21',
    'ua_hash21',
    NOW() - INTERVAL '21 days'
);

-- Assign topics to feedback based on content analysis
INSERT INTO feedback_topics (feedback_id, topic_id, relevance_score)
SELECT 
    fs.id,
    t.id,
    CASE 
        WHEN t.name = 'Work Environment' AND (fs.comments ILIKE '%environment%' OR fs.comments ILIKE '%culture%' OR fs.comments ILIKE '%team%') THEN 0.8
        WHEN t.name = 'Management' AND (fs.comments ILIKE '%management%' OR fs.comments ILIKE '%manager%' OR fs.comments ILIKE '%leadership%') THEN 0.9
        WHEN t.name = 'Compensation' AND (fs.comments ILIKE '%compensation%' OR fs.comments ILIKE '%salary%' OR fs.comments ILIKE '%pay%') THEN 0.9
        WHEN t.name = 'Career Growth' AND (fs.comments ILIKE '%growth%' OR fs.comments ILIKE '%development%' OR fs.comments ILIKE '%career%') THEN 0.8
        WHEN t.name = 'Work-Life Balance' AND (fs.comments ILIKE '%balance%' OR fs.comments ILIKE '%flexibility%' OR fs.comments ILIKE '%hours%') THEN 0.7
        WHEN t.name = 'Communication' AND (fs.comments ILIKE '%communication%' OR fs.comments ILIKE '%transparent%' OR fs.comments ILIKE '%meetings%') THEN 0.6
        ELSE 0.3
    END as relevance_score
FROM feedback_submissions fs
CROSS JOIN topics t
WHERE CASE 
    WHEN t.name = 'Work Environment' AND (fs.comments ILIKE '%environment%' OR fs.comments ILIKE '%culture%' OR fs.comments ILIKE '%team%') THEN true
    WHEN t.name = 'Management' AND (fs.comments ILIKE '%management%' OR fs.comments ILIKE '%manager%' OR fs.comments ILIKE '%leadership%') THEN true
    WHEN t.name = 'Compensation' AND (fs.comments ILIKE '%compensation%' OR fs.comments ILIKE '%salary%' OR fs.comments ILIKE '%pay%') THEN true
    WHEN t.name = 'Career Growth' AND (fs.comments ILIKE '%growth%' OR fs.comments ILIKE '%development%' OR fs.comments ILIKE '%career%') THEN true
    WHEN t.name = 'Work-Life Balance' AND (fs.comments ILIKE '%balance%' OR fs.comments ILIKE '%flexibility%' OR fs.comments ILIKE '%hours%') THEN true
    WHEN t.name = 'Communication' AND (fs.comments ILIKE '%communication%' OR fs.comments ILIKE '%transparent%' OR fs.comments ILIKE '%meetings%') THEN true
    ELSE false
END;

-- Add some analysis cache entries for demonstration
INSERT INTO analysis_cache (content_hash, model_name, result, expires_at)
VALUES
('hash_sample1', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "positive", "score": 0.85}', NOW() + INTERVAL '7 days'),
('hash_sample2', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "negative", "score": 0.78}', NOW() + INTERVAL '7 days'),
('hash_sample3', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "neutral", "score": 0.65}', NOW() + INTERVAL '7 days');