-- Seed data for Employee Feedback Analyzer
-- This file contains comprehensive sample feedback data for testing and demonstration

-- Insert sample topics first
INSERT INTO topics (name, description, keywords) VALUES
('Work Environment', 'Feedback about the physical and cultural work environment', ARRAY['office', 'culture', 'atmosphere', 'colleagues', 'team', 'environment']),
('Management', 'Feedback about leadership and management practices', ARRAY['manager', 'leadership', 'supervision', 'guidance', 'support', 'communication']),
('Compensation', 'Feedback about salary, benefits, and compensation', ARRAY['salary', 'pay', 'benefits', 'compensation', 'bonus', 'raise']),
('Career Growth', 'Feedback about professional development and growth opportunities', ARRAY['career', 'growth', 'development', 'promotion', 'learning', 'training']),
('Work-Life Balance', 'Feedback about work-life balance and flexibility', ARRAY['balance', 'flexibility', 'hours', 'remote', 'schedule', 'time']),
('Technology', 'Feedback about tools, systems, and technology', ARRAY['tools', 'software', 'systems', 'technology', 'equipment', 'IT']),
('Communication', 'Feedback about internal communication and transparency', ARRAY['communication', 'meetings', 'updates', 'transparency', 'information', 'news']),
('Recognition', 'Feedback about recognition and appreciation', ARRAY['recognition', 'appreciation', 'feedback', 'praise', 'achievement', 'reward']);

-- Comprehensive feedback submissions with diverse sentiment data
INSERT INTO feedback_submissions (
    department_id,
    is_anonymous,
    submitter_name,
    overall_rating,
    work_environment_rating,
    management_rating,
    compensation_rating,
    growth_opportunities_rating,
    comments,
    suggestions,
    redacted_comments,
    redacted_suggestions,
    contains_pii,
    sentiment_score,
    sentiment_label,
    confidence_score,
    ip_hash,
    user_agent_hash,
    submitted_at
) VALUES

-- Engineering Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    4,
    4,
    3,
    3,
    4,
    'Great team culture and interesting projects. The work environment is collaborative and supportive. However, management could be more transparent about company direction and compensation could be more competitive.',
    'Consider implementing regular 1-on-1s with managers and more transparent salary bands.',
    'Great team culture and interesting projects. The work environment is collaborative and supportive. However, management could be more transparent about company direction and compensation could be more competitive.',
    'Consider implementing regular 1-on-1s with managers and more transparent salary bands.',
    false,
    0.2,
    'positive',
    0.85,
    'hash1',
    'ua_hash1',
    NOW() - INTERVAL '1 day'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'Sarah Chen',
    5,
    5,
    4,
    4,
    5,
    'Absolutely love working here! The team is amazing, the projects are challenging, and I feel like I am constantly learning and growing. Management is supportive and the work-life balance is excellent.',
    'Keep doing what you are doing! Maybe add more team building activities.',
    'Absolutely love working here! The team is amazing, the projects are challenging, and I feel like I am constantly learning and growing. Management is supportive and the work-life balance is excellent.',
    'Keep doing what you are doing! Maybe add more team building activities.',
    false,
    0.8,
    'positive',
    0.92,
    'hash2',
    'ua_hash2',
    NOW() - INTERVAL '2 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    2,
    2,
    2,
    2,
    3,
    'The workload is overwhelming and unrealistic. Management keeps adding more projects without considering capacity. The compensation is below market rate and there is no clear path for advancement.',
    'Need better project planning and realistic deadlines. Also, please review salary bands.',
    'The workload is overwhelming and unrealistic. Management keeps adding more projects without considering capacity. The compensation is below market rate and there is no clear path for advancement.',
    'Need better project planning and realistic deadlines. Also, please review salary bands.',
    false,
    -0.7,
    'negative',
    0.88,
    'hash3',
    'ua_hash3',
    NOW() - INTERVAL '3 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'David Kim',
    4,
    4,
    4,
    3,
    4,
    'Solid engineering team with good technical challenges. The codebase is well-maintained and the development process is efficient. Management understands technical requirements well.',
    'More opportunities for technical leadership and architecture decisions.',
    'Solid engineering team with good technical challenges. The codebase is well-maintained and the development process is efficient. Management understands technical requirements well.',
    'More opportunities for technical leadership and architecture decisions.',
    false,
    0.4,
    'positive',
    0.78,
    'hash4',
    'ua_hash4',
    NOW() - INTERVAL '4 days'
),
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    true,
    null,
    1,
    1,
    1,
    1,
    2,
    'Terrible place to work. Toxic environment, poor management, unrealistic expectations, and terrible compensation. I regret joining this company.',
    'Complete overhaul of management and company culture needed.',
    'Terrible place to work. Toxic environment, poor management, unrealistic expectations, and terrible compensation. I regret joining this company.',
    'Complete overhaul of management and company culture needed.',
    false,
    -0.9,
    'negative',
    0.95,
    'hash5',
    'ua_hash5',
    NOW() - INTERVAL '5 days'
),

-- Product Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Product'),
    false,
    'Michael Rodriguez',
    4,
    4,
    4,
    3,
    4,
    'Product team has great vision and the work is meaningful. Good collaboration with engineering. However, sometimes decisions are made without enough user research and the compensation could be better.',
    'More user research before major decisions and regular salary reviews.',
    'Product team has great vision and the work is meaningful. Good collaboration with engineering. However, sometimes decisions are made without enough user research and the compensation could be better.',
    'More user research before major decisions and regular salary reviews.',
    false,
    0.1,
    'positive',
    0.75,
    'hash6',
    'ua_hash6',
    NOW() - INTERVAL '6 days'
),
(
    (SELECT id FROM departments WHERE name = 'Product'),
    true,
    null,
    3,
    3,
    3,
    3,
    3,
    'The work is okay but sometimes feels disconnected from user needs. Management is decent but could be more hands-on. Compensation is average but benefits are good.',
    'More user feedback sessions and clearer product roadmap communication.',
    'The work is okay but sometimes feels disconnected from user needs. Management is decent but could be more hands-on. Compensation is average but benefits are good.',
    'More user feedback sessions and clearer product roadmap communication.',
    false,
    0.0,
    'neutral',
    0.65,
    'hash7',
    'ua_hash7',
    NOW() - INTERVAL '7 days'
),
(
    (SELECT id FROM departments WHERE name = 'Product'),
    false,
    'Emily Watson',
    5,
    5,
    5,
    4,
    5,
    'Amazing product team! We have incredible vision, excellent user research, and great collaboration across departments. Management is supportive and the work is incredibly rewarding.',
    'Continue the excellent work! Maybe add more cross-functional workshops.',
    'Amazing product team! We have incredible vision, excellent user research, and great collaboration across departments. Management is supportive and the work is incredibly rewarding.',
    'Continue the excellent work! Maybe add more cross-functional workshops.',
    false,
    0.9,
    'positive',
    0.94,
    'hash8',
    'ua_hash8',
    NOW() - INTERVAL '8 days'
),

-- Sales Department - High Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    false,
    'James Thompson',
    5,
    4,
    5,
    5,
    4,
    'Excellent commission structure and great team support. Management is very supportive and provides good training. The work environment is energetic and motivating.',
    'Continue the great work! Maybe add more team recognition programs.',
    'Excellent commission structure and great team support. Management is very supportive and provides good training. The work environment is energetic and motivating.',
    'Continue the great work! Maybe add more team recognition programs.',
    false,
    0.9,
    'positive',
    0.95,
    'hash9',
    'ua_hash9',
    NOW() - INTERVAL '9 days'
),
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    true,
    null,
    2,
    3,
    2,
    2,
    2,
    'High pressure environment with unrealistic targets. Management is not supportive and the commission structure was recently changed for the worse. Very stressful and no work-life balance.',
    'Review targets and commission structure. Management needs better training on supporting team members.',
    'High pressure environment with unrealistic targets. Management is not supportive and the commission structure was recently changed for the worse. Very stressful and no work-life balance.',
    'Review targets and commission structure. Management needs better training on supporting team members.',
    false,
    -0.8,
    'negative',
    0.90,
    'hash10',
    'ua_hash10',
    NOW() - INTERVAL '10 days'
),
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    false,
    'Lisa Park',
    4,
    4,
    4,
    4,
    4,
    'Great sales team with strong leadership. The commission structure is fair and the work environment is collaborative. Good opportunities for career growth.',
    'More training on new product features and better CRM tools.',
    'Great sales team with strong leadership. The commission structure is fair and the work environment is collaborative. Good opportunities for career growth.',
    'More training on new product features and better CRM tools.',
    false,
    0.6,
    'positive',
    0.82,
    'hash11',
    'ua_hash11',
    NOW() - INTERVAL '11 days'
),

-- Marketing Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Marketing'),
    false,
    'Alex Johnson',
    4,
    4,
    4,
    3,
    4,
    'Creative and dynamic team with lots of interesting projects. Good collaboration across departments. Management is supportive and open to new ideas. Compensation could be more competitive.',
    'More budget for creative projects and better salary benchmarking.',
    'Creative and dynamic team with lots of interesting projects. Good collaboration across departments. Management is supportive and open to new ideas. Compensation could be more competitive.',
    'More budget for creative projects and better salary benchmarking.',
    false,
    0.3,
    'positive',
    0.80,
    'hash12',
    'ua_hash12',
    NOW() - INTERVAL '12 days'
),
(
    (SELECT id FROM departments WHERE name = 'Marketing'),
    true,
    null,
    3,
    3,
    3,
    3,
    3,
    'Decent work environment but sometimes feels chaotic with changing priorities. Management is okay but could be more organized. Compensation is average.',
    'Better project planning and clearer priorities would help.',
    'Decent work environment but sometimes feels chaotic with changing priorities. Management is okay but could be more organized. Compensation is average.',
    'Better project planning and clearer priorities would help.',
    false,
    0.0,
    'neutral',
    0.70,
    'hash13',
    'ua_hash13',
    NOW() - INTERVAL '13 days'
),
(
    (SELECT id FROM departments WHERE name = 'Marketing'),
    false,
    'Rachel Green',
    5,
    5,
    5,
    4,
    5,
    'Fantastic marketing team! We have amazing creative freedom, excellent resources, and great leadership. The work is exciting and the team is incredibly talented.',
    'Keep up the amazing work! Maybe add more industry conference opportunities.',
    'Fantastic marketing team! We have amazing creative freedom, excellent resources, and great leadership. The work is exciting and the team is incredibly talented.',
    'Keep up the amazing work! Maybe add more industry conference opportunities.',
    false,
    0.85,
    'positive',
    0.91,
    'hash14',
    'ua_hash14',
    NOW() - INTERVAL '14 days'
),

-- HR Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'HR'),
    false,
    'Jennifer Martinez',
    4,
    4,
    4,
    3,
    4,
    'Meaningful work helping employees and improving company culture. Good team collaboration and supportive management. The work-life balance is excellent.',
    'Continue focusing on employee experience and maybe add more professional development opportunities.',
    'Meaningful work helping employees and improving company culture. Good team collaboration and supportive management. The work-life balance is excellent.',
    'Continue focusing on employee experience and maybe add more professional development opportunities.',
    false,
    0.4,
    'positive',
    0.85,
    'hash15',
    'ua_hash15',
    NOW() - INTERVAL '15 days'
),
(
    (SELECT id FROM departments WHERE name = 'HR'),
    true,
    null,
    2,
    2,
    2,
    2,
    2,
    'Very stressful department with high turnover. Management is not supportive and the workload is overwhelming. Compensation is below market rate and there is no clear career path.',
    'Need better management training and more realistic workload expectations.',
    'Very stressful department with high turnover. Management is not supportive and the workload is overwhelming. Compensation is below market rate and there is no clear career path.',
    'Need better management training and more realistic workload expectations.',
    false,
    -0.6,
    'negative',
    0.82,
    'hash16',
    'ua_hash16',
    NOW() - INTERVAL '16 days'
),

-- Operations Department - Neutral to Positive
(
    (SELECT id FROM departments WHERE name = 'Operations'),
    false,
    'Robert Wilson',
    3,
    3,
    3,
    3,
    3,
    'Stable work environment with clear processes. Management is adequate but could be more innovative. Compensation is fair but growth opportunities are limited.',
    'More innovation in processes and better career development programs.',
    'Stable work environment with clear processes. Management is adequate but could be more innovative. Compensation is fair but growth opportunities are limited.',
    'More innovation in processes and better career development programs.',
    false,
    0.0,
    'neutral',
    0.68,
    'hash17',
    'ua_hash17',
    NOW() - INTERVAL '17 days'
),
(
    (SELECT id FROM departments WHERE name = 'Operations'),
    true,
    null,
    4,
    4,
    4,
    3,
    4,
    'Good team and well-organized processes. Management is supportive and the work is meaningful. Good work-life balance and reasonable workload.',
    'Keep up the good work! Maybe add more cross-training opportunities.',
    'Good team and well-organized processes. Management is supportive and the work is meaningful. Good work-life balance and reasonable workload.',
    'Keep up the good work! Maybe add more cross-training opportunities.',
    false,
    0.2,
    'positive',
    0.78,
    'hash18',
    'ua_hash18',
    NOW() - INTERVAL '18 days'
),

-- Finance Department - Mixed Sentiment
(
    (SELECT id FROM departments WHERE name = 'Finance'),
    false,
    'Amanda Davis',
    4,
    4,
    4,
    4,
    3,
    'Well-organized department with good processes. Management is professional and supportive. Compensation is competitive and benefits are excellent.',
    'More opportunities for professional development and industry certifications.',
    'Well-organized department with good processes. Management is professional and supportive. Compensation is competitive and benefits are excellent.',
    'More opportunities for professional development and industry certifications.',
    false,
    0.3,
    'positive',
    0.80,
    'hash19',
    'ua_hash19',
    NOW() - INTERVAL '19 days'
),
(
    (SELECT id FROM departments WHERE name = 'Finance'),
    true,
    null,
    2,
    2,
    2,
    2,
    2,
    'Very rigid and bureaucratic environment. Management is not flexible and the work is repetitive. Limited growth opportunities and below market compensation.',
    'Need more flexibility in processes and better career development opportunities.',
    'Very rigid and bureaucratic environment. Management is not flexible and the work is repetitive. Limited growth opportunities and below market compensation.',
    'Need more flexibility in processes and better career development opportunities.',
    false,
    -0.5,
    'negative',
    0.75,
    'hash20',
    'ua_hash20',
    NOW() - INTERVAL '20 days'
),

-- Customer Success Department - Positive Sentiment
(
    (SELECT id FROM departments WHERE name = 'Customer Success'),
    false,
    'Kevin Brown',
    4,
    4,
    4,
    3,
    4,
    'Great team culture focused on helping customers. Management is supportive and provides good training. The work is rewarding but sometimes stressful.',
    'More resources and better tools to help customers more effectively.',
    'Great team culture focused on helping customers. Management is supportive and provides good training. The work is rewarding but sometimes stressful.',
    'More resources and better tools to help customers more effectively.',
    false,
    0.2,
    'positive',
    0.82,
    'hash21',
    'ua_hash21',
    NOW() - INTERVAL '21 days'
),
(
    (SELECT id FROM departments WHERE name = 'Customer Success'),
    true,
    null,
    3,
    3,
    3,
    3,
    3,
    'Decent work environment but high stress due to customer demands. Management is okay but could be more supportive during difficult situations.',
    'Better support systems and more training on handling difficult customers.',
    'Decent work environment but high stress due to customer demands. Management is okay but could be more supportive during difficult situations.',
    'Better support systems and more training on handling difficult customers.',
    false,
    0.0,
    'neutral',
    0.70,
    'hash22',
    'ua_hash22',
    NOW() - INTERVAL '22 days'
),

-- Additional recent feedback for trend analysis
(
    (SELECT id FROM departments WHERE name = 'Engineering'),
    false,
    'Tom Anderson',
    4,
    4,
    4,
    3,
    4,
    'Recent improvements in work environment and team collaboration. Management has been more transparent lately. Still room for improvement in compensation.',
    'Continue the positive changes and consider salary adjustments.',
    'Recent improvements in work environment and team collaboration. Management has been more transparent lately. Still room for improvement in compensation.',
    'Continue the positive changes and consider salary adjustments.',
    false,
    0.3,
    'positive',
    0.85,
    'hash23',
    'ua_hash23',
    NOW() - INTERVAL '1 hour'
),
(
    (SELECT id FROM departments WHERE name = 'Product'),
    true,
    null,
    3,
    3,
    3,
    3,
    3,
    'Average experience overall. Some good projects but also some frustrating processes. Management is okay but could be more decisive.',
    'More streamlined processes and clearer decision-making would help.',
    'Average experience overall. Some good projects but also some frustrating processes. Management is okay but could be more decisive.',
    'More streamlined processes and clearer decision-making would help.',
    false,
    0.0,
    'neutral',
    0.65,
    'hash24',
    'ua_hash24',
    NOW() - INTERVAL '2 hours'
),
(
    (SELECT id FROM departments WHERE name = 'Sales'),
    false,
    'Maria Garcia',
    4,
    4,
    4,
    4,
    4,
    'Great quarter with good results. Team is motivated and management is supportive. Compensation is fair and the work environment is positive.',
    'Keep up the momentum! Maybe add more team recognition.',
    'Great quarter with good results. Team is motivated and management is supportive. Compensation is fair and the work environment is positive.',
    'Keep up the momentum! Maybe add more team recognition.',
    false,
    0.5,
    'positive',
    0.88,
    'hash25',
    'ua_hash25',
    NOW() - INTERVAL '3 hours'
);

-- Assign topics to feedback based on content analysis
INSERT INTO feedback_topics (feedback_id, topic_id, relevance_score)
SELECT 
    fs.id,
    t.id,
    CASE 
        WHEN t.name = 'Work Environment' AND (fs.comments ILIKE '%environment%' OR fs.comments ILIKE '%culture%' OR fs.comments ILIKE '%team%') THEN 0.8
        WHEN t.name = 'Management' AND (fs.comments ILIKE '%management%' OR fs.comments ILIKE '%manager%' OR fs.comments ILIKE '%leadership%') THEN 0.9
        WHEN t.name = 'Compensation' AND (fs.comments ILIKE '%compensation%' OR fs.comments ILIKE '%salary%' OR fs.comments ILIKE '%pay%') THEN 0.9
        WHEN t.name = 'Career Growth' AND (fs.comments ILIKE '%growth%' OR fs.comments ILIKE '%development%' OR fs.comments ILIKE '%career%') THEN 0.8
        WHEN t.name = 'Work-Life Balance' AND (fs.comments ILIKE '%balance%' OR fs.comments ILIKE '%flexibility%' OR fs.comments ILIKE '%hours%') THEN 0.7
        WHEN t.name = 'Communication' AND (fs.comments ILIKE '%communication%' OR fs.comments ILIKE '%transparent%' OR fs.comments ILIKE '%meetings%') THEN 0.6
        ELSE 0.3
    END as relevance_score
FROM feedback_submissions fs
CROSS JOIN topics t
WHERE CASE 
    WHEN t.name = 'Work Environment' AND (fs.comments ILIKE '%environment%' OR fs.comments ILIKE '%culture%' OR fs.comments ILIKE '%team%') THEN true
    WHEN t.name = 'Management' AND (fs.comments ILIKE '%management%' OR fs.comments ILIKE '%manager%' OR fs.comments ILIKE '%leadership%') THEN true
    WHEN t.name = 'Compensation' AND (fs.comments ILIKE '%compensation%' OR fs.comments ILIKE '%salary%' OR fs.comments ILIKE '%pay%') THEN true
    WHEN t.name = 'Career Growth' AND (fs.comments ILIKE '%growth%' OR fs.comments ILIKE '%development%' OR fs.comments ILIKE '%career%') THEN true
    WHEN t.name = 'Work-Life Balance' AND (fs.comments ILIKE '%balance%' OR fs.comments ILIKE '%flexibility%' OR fs.comments ILIKE '%hours%') THEN true
    WHEN t.name = 'Communication' AND (fs.comments ILIKE '%communication%' OR fs.comments ILIKE '%transparent%' OR fs.comments ILIKE '%meetings%') THEN true
    ELSE false
END;

-- Add some analysis cache entries for demonstration
INSERT INTO analysis_cache (content_hash, model_name, result, expires_at)
VALUES
('hash_sample1', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "positive", "score": 0.85}', NOW() + INTERVAL '7 days'),
('hash_sample2', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "negative", "score": 0.78}', NOW() + INTERVAL '7 days'),
('hash_sample3', 'cardiffnlp/twitter-roberta-base-sentiment-latest', '{"sentiment": "neutral", "score": 0.65}', NOW() + INTERVAL '7 days');